# Generated by Django 3.1.3 on 2020-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0002_auto_20201111_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(to='taskApi.Category'),
        ),
    ]
